version: "3.5"
services:
  ssv:
    image: "ssv.ssv-shifu.dnp.dappnode.eth:0.1.0"
    build:
      context: build
      args:
        UPSTREAM_VERSION: v0.3.2
    restart: unless-stopped
    volumes:
      - "ssv:/ssv"
    ports:
      - "12514:12514/tcp"
      - "13514:13514/udp"
    environment:
      CONFIG_PATH: ./config.yml
      DB_PATH: /data/db
      NETWORK: prater
      OPERATOR_PRIVATE_KEY: ""
      LOG_LEVEL: info
      EXTRA_OPTS: ""
volumes:
  ssv: {}
