version: "3.4"
services:
  ssv-shifu.dnp.dappnode.eth:
    image: "ssv-shifu.dnp.dappnode.eth:0.1.0"
    build:
      context: build
      args:
        UPSTREAM_VERSION: v0.3.4
    restart: unless-stopped
    volumes:
      - "shifu:/data"
    ports:
      - "12514:12514/TCP"
      - "13514:13514/UDP"
    environment:
      CONFIG_PATH: ./config.yml
      DB_PATH: /data/db
      NETWORK: prater
      BEACON_NODE_ADDR: "beacon-chain.prysm-prater.dappnode:3500"
      ETH1ADDR: "ws://goerli-geth.dappnode:8546"
      OPERATOR_PRIVATE_KEY: ""
      LOG_LEVEL: info
      EXTRA_OPTS: ""
volumes:
  shifu: {}
