{
 "title": "SSV Operator Node (Stage)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "ssv.ssv-shifu.dappnode" },
   {
    "name": "explorer",
    "query": "https://explorer.stage.ssv.network,https://explorer.ssv.network"
   },
   { "name": "validator_dashboard_id", "query": "ssv-shifu-XIbEQ37xx" }
  ]
 },
 "panels": [
  {
   "title": "Awaiting Min Peers (2m rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate (ssv:validator:await_min_peers{instance=~\"$instance.*\"}[2m])",
     "legendFormat": "{{pubKey}}"
    }
   ]
  },
  {
   "title": "Peer Scores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ssv:p2p:pubsub:score:inspect{instance=~\"$instance.*\"}",
     "legendFormat": "{{pid}}"
    }
   ]
  },
  { "title": "Attestation Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Attestation Data Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(ssv:beacon:attestation_data_request_duration_seconds_bucket{instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Full Flow (Excl. Att. Data Req.)",
   "type": "timeseries",
   "description": "Attestation full flow duration excluding waiting for 1/3 of slot time and attestation data request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(ssv:validator:attestation_full_flow_duration_seconds_bucket{instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "timeseries",
   "description": "Duration from proposal to commits",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(ssv:validator:consensus_duration_seconds_bucket{instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Proposal Stage",
   "type": "timeseries",
   "description": "Proposal processing ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(ssv:validator:instance_stage_duration_seconds_bucket{stage=\"proposal\",instance=~\"$instance.*\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Prepare Stage",
   "type": "timeseries",
   "description": "Prepare stage duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(ssv:validator:instance_stage_duration_seconds_bucket{stage=\"prepare\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Commit Stage",
   "type": "timeseries",
   "description": "Commit stage duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(ssv:validator:instance_stage_duration_seconds_bucket{stage=\"commit\",instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Signature Collection",
   "type": "timeseries",
   "description": "Attestation signature collection stage duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(ssv:validator:signature_collection_duration_seconds_bucket{instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Attestation Submission",
   "type": "timeseries",
   "description": "Attestation submission duration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(ssv:validator:attestation_submission_duration_seconds_bucket{instance=~\"$instance.*\"}[$__interval])) by (le) ",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Network Discovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Subnets Peers Count",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "ssv:network:subnets:known{instance=~\"$instance.*\"}"
      },
      {
       "expr": "ssv:network:subnets:connected{instance=~\"$instance.*\"}"
      },
      {
       "expr": "ssv:network:subnets:my{instance=~\"$instance.*\"}"
      }
     ]
    },
    {
     "title": "Total Connections Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 8, "y": 18 },
     "targets": [
      {
       "expr": "ssv:network:all_connected_peers{instance=~\"$instance.*\"}",
       "legendFormat": "Connections"
      }
     ]
    },
    {
     "title": "Peers Discovery Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "rate(ssv:network:discovery:found{instance=~\"$instance.*\"}[2m])",
       "legendFormat": "Found"
      },
      {
       "expr": "rate(ssv:network:discovery:rejected{instance=~\"$instance.*\"}[2m])",
       "legendFormat": "Rejected"
      }
     ]
    },
    {
     "title": "DiscV5 Ping/Pong",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 10, "y": 27 },
     "targets": [
      {
       "expr": "ssv:network:discovery:enr_ping{instance=~\"$instance.*\"}",
       "legendFormat": "Ping"
      },
      {
       "expr": "ssv:network:discovery:enr_pong{instance=~\"$instance.*\"}",
       "legendFormat": "Pong"
      }
     ]
    },
    {
     "title": "Topics Peers Distribution ",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 16, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "ssv:network:connected_peers{instance=~\"$instance.*\"}",
       "legendFormat": "{{pubKey}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O (1m rate)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{pod=~\"$instance.*\"}[1m])) by (pod)",
       "legendFormat": "in {{pod}}"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{pod=~\"$instance.*\"}[1m])) by (pod)",
       "legendFormat": "out {{pod}}"
      }
     ]
    },
    {
     "title": "Pubsub Messages (2m rate)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 19 },
     "targets": [
      {
       "expr": "sum (rate(ssv:p2p:pubsub:msg:in{instance=~\"$instance.*\"}[2m]))",
       "legendFormat": "inbound"
      },
      {
       "expr": "sum (rate(ssv:p2p:pubsub:msg:out{instance=~\"$instance.*\"}[2m]))",
       "legendFormat": "outbound"
      }
     ]
    },
    {
     "title": "Incoming Topic Messages (2m rate)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate (ssv:p2p:pubsub:msg:in{instance=~\"$instance.*\"}[2m])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Outgoing Topic Messages (2m rate)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 11, "x": 11, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate (ssv:p2p:pubsub:msg:out{instance=~\"$instance.*\"}[2m])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Pubsub Trace distribution (2m rate)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 13, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "rate(ssv:network:pubsub:trace{instance=~\"$instance.*\"}[2m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Stream Protocols",
     "type": "table",
     "gridPos": { "h": 10, "w": 9, "x": 13, "y": 40 },
     "targets": [
      {
       "expr": "ssv:p2p:streams:res{instance=~\"$instance.*\"}",
       "legendFormat": "Responses"
      },
      {
       "expr": "ssv:p2p:streams:req:count{instance=~\"$instance.*\"}",
       "legendFormat": "Requests"
      },
      {
       "expr": "ssv:p2p:streams:req:success{instance=~\"$instance.*\"}",
       "legendFormat": "Successful Requests"
      },
      {
       "expr": "ssv:p2p:streams:req:active{instance=~\"$instance.*\"}",
       "legendFormat": "Active"
      }
     ]
    }
   ]
  },
  {
   "title": "Validators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validator Status",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "count(ssv:validator:status{instance=~\"$instance.*\"} == 3)",
       "legendFormat": "Active"
      },
      {
       "expr": "count(ssv:validator:status{instance=~\"$instance.*\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Change Round Distribution ",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ssv:validator:ibft_stage{instance=~\"$instance.*\"} == 4)",
       "legendFormat": "All Change Round"
      },
      {
       "expr": "count(ssv:validator:ibft_round{instance=~\"$instance.*\"} > 2)",
       "legendFormat": "Total Above Round 2"
      },
      {
       "expr": "count_values(\"round\", ssv:validator:ibft_round{instance=~\"$instance.*\"} > 2)",
       "legendFormat": "round {{ round }}"
      }
     ]
    },
    {
     "title": "Change Round",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 14, "y": 20 },
     "targets": [
      {
       "expr": "count(ssv:validator:ibft_round{instance=~\"$instance.*\"} > 2)",
       "legendFormat": "All Change Round"
      }
     ]
    },
    {
     "title": "Validators (Attestation)",
     "type": "table",
     "description": "Information on attestation duties for all validators registered to an operator",
     "gridPos": { "h": 13, "w": 23, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "ssv:validator:ibft_stage{instance=~\"$instance.*\"}"
      },
      {
       "expr": "ssv:validator:ibft_highest_decided{instance=~\"$instance.*\"}"
      },
      {
       "expr": "ssv:network:connected_peers{instance=~\"$instance.*\"}"
      },
      {
       "expr": "ssv:validator:ibft_current_sequence{instance=~\"$instance.*\"}"
      },
      {
       "expr": "ssv:validator:ibft_round{instance=~\"$instance.*\"}"
      },
      {
       "expr": "ssv:validator:running_ibfts_count{instance=~\"$instance.*\"}"
      },
      {
       "expr": "ssv:validator:ibft_current_slot{instance=~\"$instance.*\"}"
      },
      {
       "expr": "ssv:validator:status{instance=~\"$instance.*\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "QBFT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processed Messages by Workers (2m rate)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "rate (ssv:worker:msg:process{instance=~\"$instance.*\"}[2m])",
       "legendFormat": "Processed Messages Rate"
      }
     ]
    },
    {
     "title": "QBFT Message Queues",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 11, "y": 21 },
     "targets": [
      {
       "expr": "sum by (v) (ssv:ibft:msgq:ratio{instance=~\"$instance.*\"})",
       "legendFormat": "Messages"
      }
     ]
    },
    {
     "title": "QBFT Message Queue Size",
     "type": "table",
     "gridPos": { "h": 10, "w": 14, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "ssv:ibft:msgq:ratio{instance=~\"$instance.*\"}"
      }
     ]
    },
    {
     "title": "QBFT Message Queue Size (Types)",
     "type": "table",
     "gridPos": { "h": 11, "w": 17, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "ssv:ibft:msgq:ratio{instance=~\"$instance.*\"}"
      }
     ]
    },
    {
     "title": "Message Processing Duration",
     "type": "heatmap",
     "description": "Message processing duration (seconds)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum(increase(ssv:ibft:msgq:processing_duration_seconds_bucket{instance=~\"$instance.*\"}[$__interval])) by (le) ",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version Distribution",
     "type": "table",
     "gridPos": { "h": 12, "w": 15, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "ssv:network:peers_identity{instance=~\"ssv-exporter.*\"}"
      }
     ]
    },
    {
     "title": "Known Operators",
     "type": "table",
     "gridPos": { "h": 13, "w": 23, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "ssv:network:peers_identity{instance=~\"$instance.*\"}"
      },
      { "expr": "ssv:exporter:operator_index{}" }
     ]
    }
   ]
  },
  {
   "title": "Node Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Health Status",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ssv:beacon:node_status{instance=~\"$instance.*\"}",
       "legendFormat": "Beacon"
      },
      {
       "expr": "ssv:eth1:node_status{instance=~\"$instance.*\"}",
       "legendFormat": "ETH1"
      },
      {
       "expr": "ssv:node_status{instance=~\"$instance.*\"}",
       "legendFormat": "SSV Operator"
      },
      {}
     ]
    },
    {
     "title": "Operator Node Health",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 4, "x": 9, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "ssv:node_status{instance=~\"$instance.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ETH1 Node Health",
     "type": "timeseries",
     "description": "Status of the connected ETH1 node",
     "gridPos": { "h": 5, "w": 4, "x": 13, "y": 23 },
     "targets": [
      {
       "expr": "ssv:eth1:node_status{instance=~\"$instance.*\"}"
      }
     ]
    },
    {
     "title": "Beacon Node Health",
     "type": "timeseries",
     "description": "Status of the connected beacon node",
     "gridPos": { "h": 5, "w": 4, "x": 17, "y": 23 },
     "targets": [
      {
       "expr": "ssv:beacon:node_status{instance=~\"$instance.*\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory (Go)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{instance=~\"$instance.*\"}",
       "legendFormat": "sys_bytes"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{instance=~\"$instance.*\"}",
       "legendFormat": "heap_idle_bytes"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance.*\"}",
       "legendFormat": "heap_inuse_bytes"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance.*\"}",
       "legendFormat": "stack_inuse_bytes"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", pod=~\"$instance.*\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Memory Usage (k8s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\", pod=~\"$instance.*\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{instance=~\"$instance.*\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"$instance\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Network I/O (1m rate)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{pod=~\"$instance.*\"}[1m])) by (pod)",
       "legendFormat": "in {{pod}}"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{pod=~\"$instance.*\"}[1m])) by (pod)",
       "legendFormat": "out {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}