{
 "title": "SSV Validator",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "query": "ssv.ssv-shifu.dappnode" },
   {
    "name": "pubkey",
    "label": "Public Key",
    "query": {
     "query": "ssv:network:connected_peers{instance=~\"$instance.*\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:status{instance=~\"$instance.*\",pubKey=\"$pubkey\"}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:network:connected_peers{instance=~\"$instance.*\",pubKey=\"$pubkey\"}",
     "legendFormat": "{{pubKey}}"
    }
   ]
  },
  { "title": "Attestations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Highest Decided",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:ibft_highest_decided{instance=~\"$instance.*\",pubKey=\"$pubkey\"}",
     "legendFormat": "{{pubKey}}"
    }
   ]
  },
  {
   "title": "IBFT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:running_ibfts_count{instance=~\"$instance.*\",pubKey=\"$pubkey\"}"
    }
   ]
  },
  {
   "title": "Stage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:ibft_stage{instance=~\"$instance.*\",pubKey=\"$pubkey\"}"
    }
   ]
  },
  {
   "title": "Current Sequence",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:ibft_current_sequence{instance=~\"$instance.*\",pubKey=\"$pubkey\"}"
    }
   ]
  },
  {
   "title": "Current Slot",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:ibft_current_slot{instance=~\"$instance.*\",pubKey=\"$pubkey\"}"
    }
   ]
  },
  {
   "title": "Round",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv:validator:ibft_round{instance=~\"$instance.*\",pubKey=\"$pubkey\"}"
    }
   ]
  }
 ]
}